import org.apache.hadoop.io.*;
import org.apache.hadoop.mapreduce.*;

import java.io.IOException;

/**
 * SecondarySortMapper implements the map() function for
 * the secondary sort design pattern.
 *
 * @author Mahmoud Parsian
 *
 */
public class SecondarySortMapper
    extends Mapper<LongWritable, Text, Sale, Text> {
    @Override
    /**
     * @param key is generated by Hadoop (ignored here)
     * @param value has this format: "YYYY,MM,DD,temperature"
     */
    public void map(LongWritable key, Text value, Context context)
        throws IOException, InterruptedException {
        String line = value.toString();
        String[] tokens = line.split(",");
        context.write(new Sale(tokens[1], tokens[2], tokens[0]), new Text(tokens[2] + ", " + tokens[0]));
    }
}
